---
workstation_default_api_interaction: []

workstation_default_groups_additional_create: []

workstation_default_groups_additional:
  - "libvirt"

workstation_sysctl_parameters:
  - name: "vm.swappiness"
    value: 1

workstation_default_required_dirs:
  - path: "{{ workstation_homedir }}/.config/Code/User"
    owner: "{{ workstation_username }}"
    group: "{{ workstation_group_primary }}"
    mode: "0755"

  - path: "{{ workstation_homedir }}/.config/terminator"
    owner: "{{ workstation_username }}"
    group: "{{ workstation_group_primary }}"
    mode: "0755"

  - path: "{{ workstation_homedir }}/.local/bin"
    owner: "{{ workstation_username }}"
    group: "{{ workstation_group_primary }}"
    mode: "0755"

  - path: "{{ workstation_homedir }}/.ssh"
    owner: "{{ workstation_username }}"
    group: "{{ workstation_group_primary }}"
    mode: "0700"

  - path: "{{ workstation_homedir }}/git"
    owner: "{{ workstation_username }}"
    group: "{{ workstation_group_primary }}"
    mode: "0755"

workstation_default_required_files:
  - src: "code-settings.json"
    dest: "{{ workstation_homedir }}/.config/Code/User/settings.json"
    owner: "{{ workstation_username }}"
    group: "{{ workstation_group_primary }}"
    mode: "0644"

  - src: "bluetooth-main.conf"
    dest: "/etc/bluetooth/main.conf"
    owner: "root"
    group: "root"
    mode: "0644"

workstation_default_rpm_repos:
  - name: "google-chrome"
    description: "Google Chrome official stable repository"
    baseurl: "http://dl.google.com/linux/chrome/rpm/stable/x86_64"
    gpgcheck: yes
    gpgkey: "https://dl.google.com/linux/linux_signing_key.pub"
    enabled: yes

  - name: "slack"
    description: "Slack repository"
    baseurl: "https://packagecloud.io/slacktechnologies/slack/fedora/21/x86_64"
    gpgcheck: no
    enabled: yes

workstation_default_rpm_repo_packages:
  - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-42.noarch.rpm"
  - "https://download.teamviewer.com/download/linux/teamviewer.x86_64.rpm"

workstation_default_rpm_packages:
  - "@virtualization"
  - "awscli2"
  - "code"
  - "bluez-hcidump"
  - "bluez-hid2hci"
  - "bluez-libs-devel"
  - "bluez-mesh"
  - "bluez-tools"
  - "exfat-utils"
  - "fuse-exfat"
  - "gimp"
  - "google-chrome-stable"
  - "gnome-extensions-app"
  - "gnome-shell-extension-gpaste"
  - "gnome-shell-extension-appindicator"
  - "gnome-tweaks"
  - "python3-psutil"
  - "remmina"
  - "terminator"
  - "transmission"
  - "vim-default-editor"
  - "vlc"
  - "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm"

workstation_default_rpm_packages_remove:
  - "nano-default-editor"

workstation_default_git_repositories: {}

workstation_default_required_system_templates:
  - src: "99-hidraw-permissions.rules.j2"
    dest: "/etc/udev/rules.d/99-hidraw-permissions.rules"
    backup: no
    owner: "root"
    group: "root"
    mode: "0644"

workstation_default_required_templates:
  - src: "bashrc.j2"
    dest: "{{ workstation_homedir }}/.bashrc"
    backup: no
    owner: "{{ workstation_username }}"
    group: "{{ workstation_group_primary }}"
    mode: "0644"

  - src: "ssh-config.j2"
    dest: "{{ workstation_homedir }}/.ssh/config"
    backup: no
    owner: "{{ workstation_username }}"
    group: "{{ workstation_group_primary }}"
    mode: "0600"

  - src: "terminator-config.j2"
    dest: "{{ workstation_homedir }}/.config/terminator/config"
    backup: no
    owner: "{{ workstation_username }}"
    group: "{{ workstation_group_primary }}"
    mode: "0640"

workstation_default_enabled_systemd_units: []

workstation_default_dconf:
  - key: "/org/gnome/desktop/interface/color-scheme"
    state: "present"
    value: "'prefer-dark'"

  - key: "/org/gnome/desktop/interface/gtk-theme"
    state: "present"
    value: "'Adwaita'"

  - key: "/org/gnome/desktop/interface/show-battery-percentage"
    state: "present"
    value: "true"

  - key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll"
    state: "present"
    value: "false"

  - key: "/org/gnome/desktop/peripherals/touchpad/two-finger-scrolling-enabled"
    state: "present"
    value: "true"

  - key: "/org/gnome/shell/enabled-extensions"
    state: "present"
    value:
      - "appindicatorsupport@rgcjonas.gmail.com"
      - "background-logo@fedorahosted.org"
      - "GPaste@gnome-shell-extensions.gnome.org"
      - "window-list@gnome-shell-extensions.gcampax.github.com"

  - key: "/org/gnome/shell/extensions/window-list/show-on-all-monitors"
    state: "present"
    value: "true"

workstation_default_download_files: []

workstation_default_run_command:
  - code --install-extension hashicorp.terraform
  - code --install-extension ms-azuretools.vscode-docker
  - code --install-extension ms-vscode-remote.remote-containers
  - code --install-extension streetsidesoftware.code-spell-checker

workstation_default_run_command_root: []
  #- grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"

workstation_default_cleanup_files: []

workstation_docker_enabled: False
